### ISSUE TITLE
The script doesn't detect the drive when you plug it in. 

### ISSUE THREAD

**Issue by Jatotz** [scawp/Steam-Deck.Mount-External-Drive#1]
If you run the script in gaming mode and plug the drive in, nothing happens at all.

**Comment by b00mfargl3** [comment]
> 

same issue.

**Comment by andrewbaker-uk** [comment]
@scawp I'm hitting the same issue. I'm seeing this when running systemctl status 

external-drive-mount@sdc1.service - Mount External Drive on sdc1
     Loaded: loaded (/etc/systemd/system/external-drive-mount@.service; static)
     Active: active (exited) since Tue 2022-09-13 11:22:08 IST; 22s ago
    Process: 3365 ExecStart=/home/deck/repo/Steam-Deck.Mount-External-Drive/automount.sh add sdc1 (code=exite>
   Main PID: 3365 (code=exited, status=0/SUCCESS)
        CPU: 22ms

Sep 13 11:22:08 steamdeck systemd[1]: Starting Mount External Drive on sdc1...
Sep 13 11:22:08 steamdeck automount.sh[3370]: lsblk: /dev/sdc1: not a block device
Sep 13 11:22:08 steamdeck systemd[1]: Finished Mount External Drive on sdc1.

**Comment by scawp** [comment]
Hey thanks for the logs, I've just pushed an update to [automount.sh](https://github.com/scawp/Steam-Deck.Mount-External-Drive/blob/main/automount.sh) this should fix few issues and also adds some better output for viewing issues with systemctl status external-drive-mount@[sda1/sda2/sdd1 etc etc].servce. could you do a git pull and see if this has resolved things?

**Comment by andrewbaker-uk** [comment]
Confirm now working - drive mounts as expected in desktop and game mode.

Thanks for fixing @scawp
