### ISSUE TITLE
doesn't automount my USB drive

### ISSUE THREAD

**Issue by hexdsl** [scawp/Steam-Deck.Mount-External-Drive#4]
Hi.

GREAT video and great project!

I followed all steps but by disk doesnt auto mount :(

**Comment by scawp** [comment]
I've just pushed an update [automount.sh](https://github.com/scawp/Steam-Deck.Mount-External-Drive/blob/main/automount.sh) this should fix few issues and also adds some better output for viewing issues with `systemctl status external-drive-mount@[sda1/sda2/sdd1 etc etc].servce`. could you do a `git pull` and see if this has resolved things?

**Comment by hexdsl** [comment]
Update worked perfectly! !!! 

I'm installing things to it right now and ill update you if it all goes wrong in the future~!!! :D 

I hope you dont mind but i made a youtube video talking about your awesome little tool! - [here](https://youtu.be/j5sci66hs0k)

**Comment by scawp** [comment]
Awesome!
