### ISSUE TITLE
Steam forgets drive on unplug

### ISSUE THREAD

**Issue by foxt** [scawp/Steam-Deck.Mount-External-Drive#6]
I'm using the Quick-Auto-Mount-Only but and it works  fine, but whenever I unplug the drive Steam "forgets" the drive and I have to go to desktop mode and re add the drive. The drive is remounted (i can access it through SSH) but it doesn't appear in Steam.

**Comment by scawp** [comment]
This has worked fine for me for a long time, until today when it stopped working! Fix inbound.

**Comment by scawp** [comment]
pushed an update it `should` work, I'm getting inconsistent results to be honest, would appreciate a second opinion

**Comment by foxt** [comment]
you have a syntax error on line 57 :p 

```
Sep 29 23:54:06 steamdeck automount.sh[5196]: /home/deck/.local/share/scawp/SDMED/automount.sh: line 57: syntax error near unexpected token `fi'
Sep 29 23:54:06 steamdeck automount.sh[5196]: /home/deck/.local/share/scawp/SDMED/automount.sh: line 57: `  fi'
```

**Comment by scawp** [comment]
Thanks! Bad merge, my bad for not checking properly, cheers for the debugging!
